AWSTemplateFormatVersion: 2010-09-09
Description: CreateVPCEndpointSSM com.amazonaws.[region].ssm, ec2messages,ssmmessages
Parameters:
  VPCid:
    Description: VPCID
    Type: AWS::EC2::VPC::Id
  CidrBlock:
    Description: VPC-CidrBlock
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
  Subnetid:
    Description: SubnetID
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  secGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join
                  - '-'
                  - - !Ref AWS::StackName
                    - 'sg'
      GroupDescription: for vpc-endpoint-ssm
      VpcId:
        Ref: VPCid
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp:
          Ref: CidrBlock
  SSMep:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref secGroup
      ServiceName: com.amazonaws.ap-northeast-1.ssm
      SubnetIds:
        Ref: Subnetid
      VpcEndpointType: Interface
      VpcId:
        Ref: VPCid
  EC2MessageEp:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref secGroup
      ServiceName: com.amazonaws.ap-northeast-1.ec2messages
      SubnetIds:
        Ref: Subnetid
      VpcEndpointType: Interface
      VpcId:
        Ref: VPCid
  SSMMessageEp:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref secGroup
      ServiceName: com.amazonaws.ap-northeast-1.ssmmessages
      SubnetIds:
        Ref: Subnetid
      VpcEndpointType: Interface
      VpcId:
        Ref: VPCid